version: '3.9'

services:

  web:
    build: ./web
    container_name: visitor-app

    ports:
      - "5000:5000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - visitor-network

    restart: always

    labels:
      project: "visitor-management-system"
      environment: "dev"

  db:
    image: postgres:15
    container_name: visitor-db

    environment:
      POSTGRES_DB: visitors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - visitor-network

    restart: always

    labels:
      project: "visitor-management-system"
      service: "database"

  redis:
    image: redis:7
    container_name: visitor-redis

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

    networks:
      - visitor-network

    restart: always

    labels:
      project: "visitor-management-system"
      service: "cache"

networks:
  visitor-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
